In [15]:
import os

print(os.getcwd())

d:\NuralRetail\notebooks

In [16]:
# =========================================================
# 📦 Imports
# =========================================================

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

from sklearn.preprocessing import MinMaxScaler

In [17]:
# =========================================================
# 📂 Load Dataset
# =========================================================

df = pd.read_csv("../data/processed/cleaned_retail_data.csv")

df.head()

,invoiceno,stockcode,description,quantity,invoicedate,unitprice,customerid,country,totalprice,total_amount,year,month,day,day_of_week,weekofyear,hour,year_month,log_quantity,log_total_amount
0,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,30.0,2009,12,1,Tuesday,49,7,2009-12,3.218876,3.433987
1,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom,39.6,39.6,2009,12,1,Tuesday,49,7,2009-12,3.218876,3.703768
2,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,30.0,2009,12,1,Tuesday,49,7,2009-12,3.218876,3.433987
3,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom,30.6,30.6,2009,12,1,Tuesday,49,7,2009-12,2.564949,3.453157
4,489435,22195,HEART MEASURING SPOONS LARGE,24,2009-12-01 07:46:00,1.65,13085.0,United Kingdom,39.6,39.6,2009,12,1,Tuesday,49,7,2009-12,3.218876,3.703768

In [18]:
# =========================================================
# 🧹 Basic Cleaning
# =========================================================

df.dropna(inplace=True)

df = df[df["quantity"] > 0]

df = df[df["unitprice"] > 0]

df["invoicedate"] = pd.to_datetime(df["invoicedate"])

df.head()

,invoiceno,stockcode,description,quantity,invoicedate,unitprice,customerid,country,totalprice,total_amount,year,month,day,day_of_week,weekofyear,hour,year_month,log_quantity,log_total_amount
0,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,30.0,2009,12,1,Tuesday,49,7,2009-12,3.218876,3.433987
1,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom,39.6,39.6,2009,12,1,Tuesday,49,7,2009-12,3.218876,3.703768
2,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,30.0,2009,12,1,Tuesday,49,7,2009-12,3.218876,3.433987
3,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom,30.6,30.6,2009,12,1,Tuesday,49,7,2009-12,2.564949,3.453157
4,489435,22195,HEART MEASURING SPOONS LARGE,24,2009-12-01 07:46:00,1.65,13085.0,United Kingdom,39.6,39.6,2009,12,1,Tuesday,49,7,2009-12,3.218876,3.703768

In [19]:
# =========================================================
# 🧹 Basic Cleaning
# =========================================================

df.dropna(inplace=True)

df = df[df["quantity"] > 0]

df = df[df["unitprice"] > 0]

df["invoicedate"] = pd.to_datetime(df["invoicedate"])

df.head()

,invoiceno,stockcode,description,quantity,invoicedate,unitprice,customerid,country,totalprice,total_amount,year,month,day,day_of_week,weekofyear,hour,year_month,log_quantity,log_total_amount
0,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,30.0,2009,12,1,Tuesday,49,7,2009-12,3.218876,3.433987
1,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom,39.6,39.6,2009,12,1,Tuesday,49,7,2009-12,3.218876,3.703768
2,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,30.0,2009,12,1,Tuesday,49,7,2009-12,3.218876,3.433987
3,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom,30.6,30.6,2009,12,1,Tuesday,49,7,2009-12,2.564949,3.453157
4,489435,22195,HEART MEASURING SPOONS LARGE,24,2009-12-01 07:46:00,1.65,13085.0,United Kingdom,39.6,39.6,2009,12,1,Tuesday,49,7,2009-12,3.218876,3.703768

In [20]:
# =========================================================
# 📦 Inventory Aggregation
# =========================================================

df["revenue"] = df["quantity"] * df["unitprice"]

inventory_df = df.groupby("stockcode").agg({

    "quantity": ["sum", "mean", "std"],
    "revenue": "sum",
    "unitprice": "mean"

}).reset_index()

In [21]:
# =========================================================
# 🏷️ Rename Columns
# =========================================================

inventory_df.columns = [

    "SKU",
    "TotalDemand",
    "AvgDemand",
    "DemandStd",
    "AnnualRevenue",
    "AvgUnitPrice"

]

inventory_df.head()

      SKU  TotalDemand  AvgDemand  DemandStd  AnnualRevenue  AvgUnitPrice
0   10002         3225  11.727273  10.271949        2724.87      0.847636
1   10080          303  11.222222  11.195237         124.61      0.509259
2   10109            4   4.000000        NaN           1.68      0.420000
3   10120          648  10.451613  12.415851         136.08      0.210000
4  10123C          532  11.822222  29.370895         175.88      0.623778

In [22]:
# =========================================================
# 🧹 Handle Missing Std
# =========================================================

inventory_df["DemandStd"] = (
    inventory_df["DemandStd"]
    .fillna(0)
)

In [23]:
# =========================================================
# 🏭 Simulated Inventory Features
# =========================================================

np.random.seed(42)

inventory_df["LeadTime"] = np.random.randint(1, 15, len(inventory_df))

inventory_df["OrderingCost"] = np.random.randint(
    50,
    500,
    len(inventory_df)
)

inventory_df["HoldingCost"] = np.random.randint(
    5,
    50,
    len(inventory_df)
)


inventory_df.head()

,SKU,TotalDemand,AvgDemand,DemandStd,AnnualRevenue,AvgUnitPrice,LeadTime,OrderingCost,HoldingCost
0,10002,3225,11.727273,10.271949,2724.87,0.847636,7,387,49
1,10080,303,11.222222,11.195237,124.61,0.509259,4,297,18
2,10109,4,4.000000,0.000000,1.68,0.420000,13,403,15
3,10120,648,10.451613,12.415851,136.08,0.210000,11,176,46
4,10123C,532,11.822222,29.370895,175.88,0.623778,8,124,42

In [24]:
# =========================================================
# 📦 Economic Order Quantity (EOQ)
# =========================================================

inventory_df["EOQ"] = np.sqrt(

    (
        2 *
        inventory_df["TotalDemand"] *
        inventory_df["OrderingCost"]
    )
    /
    inventory_df["HoldingCost"]

)

inventory_df.head()

,SKU,TotalDemand,AvgDemand,DemandStd,AnnualRevenue,AvgUnitPrice,LeadTime,OrderingCost,HoldingCost,EOQ
0,10002,3225,11.727273,10.271949,2724.87,0.847636,7,387,49,225.702983
1,10080,303,11.222222,11.195237,124.61,0.509259,4,297,18,99.995000
2,10109,4,4.000000,0.000000,1.68,0.420000,13,403,15,14.660605
3,10120,648,10.451613,12.415851,136.08,0.210000,11,176,46,70.417389
4,10123C,532,11.822222,29.370895,175.88,0.623778,8,124,42,56.047599

In [25]:
# =========================================================
# 🛡️ Safety Stock
# =========================================================

Z = 1.65

inventory_df["SafetyStock"] = (

    Z *
    inventory_df["DemandStd"] *
    np.sqrt(inventory_df["LeadTime"])

)

inventory_df.head()

,SKU,TotalDemand,AvgDemand,DemandStd,AnnualRevenue,AvgUnitPrice,LeadTime,OrderingCost,HoldingCost,EOQ,SafetyStock
0,10002,3225,11.727273,10.271949,2724.87,0.847636,7,387,49,225.702983,44.842088
1,10080,303,11.222222,11.195237,124.61,0.509259,4,297,18,99.995000,36.944282
2,10109,4,4.000000,0.000000,1.68,0.420000,13,403,15,14.660605,0.000000
3,10120,648,10.451613,12.415851,136.08,0.210000,11,176,46,70.417389,67.944887
4,10123C,532,11.822222,29.370895,175.88,0.623778,8,124,42,56.047599,137.071171

In [26]:
# =========================================================
# 🔁 Reorder Point
# =========================================================

inventory_df["ReorderPoint"] = (

    inventory_df["AvgDemand"] *
    inventory_df["LeadTime"]

) + inventory_df["SafetyStock"]

inventory_df.head()

,SKU,TotalDemand,AvgDemand,DemandStd,AnnualRevenue,AvgUnitPrice,LeadTime,OrderingCost,HoldingCost,EOQ,SafetyStock,ReorderPoint
0,10002,3225,11.727273,10.271949,2724.87,0.847636,7,387,49,225.702983,44.842088,126.932997
1,10080,303,11.222222,11.195237,124.61,0.509259,4,297,18,99.995000,36.944282,81.833171
2,10109,4,4.000000,0.000000,1.68,0.420000,13,403,15,14.660605,0.000000,52.000000
3,10120,648,10.451613,12.415851,136.08,0.210000,11,176,46,70.417389,67.944887,182.912629
4,10123C,532,11.822222,29.370895,175.88,0.623778,8,124,42,56.047599,137.071171,231.648949

In [27]:
inventory_df['current_stock'] = (

    inventory_df['ReorderPoint']

    *

    np.random.uniform(0.5, 1.5, len(inventory_df))
).astype(int)

In [28]:
# =========================================================
# 📊 ABC Classification
# =========================================================

inventory_df = inventory_df.sort_values(
    by="AnnualRevenue",
    ascending=False
)

inventory_df["CumulativeRevenue"] = (

    inventory_df["AnnualRevenue"].cumsum()
    /
    inventory_df["AnnualRevenue"].sum()

)

In [29]:
def abc_class(x):

    if x <= 0.80:
        return "A"

    elif x <= 0.95:
        return "B"

    else:
        return "C"

In [30]:
inventory_df["ABC_Class"] = (
    inventory_df["CumulativeRevenue"]
    .apply(abc_class)
)

inventory_df.head()

,SKU,TotalDemand,AvgDemand,DemandStd,AnnualRevenue,AvgUnitPrice,LeadTime,OrderingCost,HoldingCost,EOQ,SafetyStock,ReorderPoint,current_stock,CumulativeRevenue,ABC_Class
4036,85123A,22782,5.990534,3.506200,66919.40,2.947526,13,341,14,1053.474659,20.858945,98.735884,70,0.007718,A
4014,85099B,24155,9.033283,5.676002,48247.80,2.001975,9,146,27,511.108454,28.096210,109.395761,67,0.013282,A
1599,22423,3494,1.722880,0.749365,44534.26,12.781810,5,272,31,247.616769,2.764792,11.379191,13,0.018419,A
3786,84879,26243,12.082413,6.159490,44302.67,1.688232,2,367,11,1323.300351,14.372876,38.537701,38,0.023528,A
244,20725,19743,8.319848,5.311393,32585.55,1.657585,1,192,13,763.660819,8.763798,17.083646,9,0.027286,A

In [31]:
# =========================================================
# 📈 Coefficient of Variation
# =========================================================

inventory_df["CV"] = (

    inventory_df["DemandStd"]
    /
    inventory_df["AvgDemand"]

)

inventory_df["CV"] = inventory_df["CV"].fillna(0)

In [32]:
def xyz_class(cv):

    if cv <= 0.5:
        return "X"

    elif cv <= 1:
        return "Y"

    else:
        return "Z"

In [33]:
inventory_df["XYZ_Class"] = (
    inventory_df["CV"]
    .apply(xyz_class)
)

inventory_df.head()

,SKU,TotalDemand,AvgDemand,DemandStd,AnnualRevenue,AvgUnitPrice,LeadTime,OrderingCost,HoldingCost,EOQ,SafetyStock,ReorderPoint,current_stock,CumulativeRevenue,ABC_Class,CV,XYZ_Class
4036,85123A,22782,5.990534,3.506200,66919.40,2.947526,13,341,14,1053.474659,20.858945,98.735884,70,0.007718,A,0.585290,Y
4014,85099B,24155,9.033283,5.676002,48247.80,2.001975,9,146,27,511.108454,28.096210,109.395761,67,0.013282,A,0.628343,Y
1599,22423,3494,1.722880,0.749365,44534.26,12.781810,5,272,31,247.616769,2.764792,11.379191,13,0.018419,A,0.434949,X
3786,84879,26243,12.082413,6.159490,44302.67,1.688232,2,367,11,1323.300351,14.372876,38.537701,38,0.023528,A,0.509790,Y
244,20725,19743,8.319848,5.311393,32585.55,1.657585,1,192,13,763.660819,8.763798,17.083646,9,0.027286,A,0.638400,Y

In [34]:
# =========================================================
# 🧠 ABC-XYZ Matrix
# =========================================================

inventory_df["ABC_XYZ"] = (

    inventory_df["ABC_Class"]
    +
    inventory_df["XYZ_Class"]

)

inventory_df.head()

,SKU,TotalDemand,AvgDemand,DemandStd,AnnualRevenue,AvgUnitPrice,LeadTime,OrderingCost,HoldingCost,EOQ,SafetyStock,ReorderPoint,current_stock,CumulativeRevenue,ABC_Class,CV,XYZ_Class,ABC_XYZ
4036,85123A,22782,5.990534,3.506200,66919.40,2.947526,13,341,14,1053.474659,20.858945,98.735884,70,0.007718,A,0.585290,Y,AY
4014,85099B,24155,9.033283,5.676002,48247.80,2.001975,9,146,27,511.108454,28.096210,109.395761,67,0.013282,A,0.628343,Y,AY
1599,22423,3494,1.722880,0.749365,44534.26,12.781810,5,272,31,247.616769,2.764792,11.379191,13,0.018419,A,0.434949,X,AX
3786,84879,26243,12.082413,6.159490,44302.67,1.688232,2,367,11,1323.300351,14.372876,38.537701,38,0.023528,A,0.509790,Y,AY
244,20725,19743,8.319848,5.311393,32585.55,1.657585,1,192,13,763.660819,8.763798,17.083646,9,0.027286,A,0.638400,Y,AY

In [35]:
# =========================================================
# ☠️ Dead Stock Analytics
# =========================================================

inventory_df["DaysSinceSale"] = np.random.randint(
    1,
    365,
    len(inventory_df)
)

inventory_df["TurnoverRatio"] = (

    inventory_df["TotalDemand"]
    /
    inventory_df["current_stock"]

)

In [36]:
inventory_df["DeadStockScore"] = (

    inventory_df["DaysSinceSale"] * 0.4

    +

    inventory_df["HoldingCost"] * 0.3

    -

    inventory_df["TurnoverRatio"] * 0.3

)

inventory_df.head()

,SKU,TotalDemand,AvgDemand,DemandStd,AnnualRevenue,AvgUnitPrice,LeadTime,OrderingCost,HoldingCost,EOQ,...,ReorderPoint,current_stock,CumulativeRevenue,ABC_Class,CV,XYZ_Class,ABC_XYZ,DaysSinceSale,TurnoverRatio,DeadStockScore
4036,85123A,22782,5.990534,3.506200,66919.40,2.947526,13,341,14,1053.474659,...,98.735884,70,0.007718,A,0.585290,Y,AY,121,325.457143,-45.037143
4014,85099B,24155,9.033283,5.676002,48247.80,2.001975,9,146,27,511.108454,...,109.395761,67,0.013282,A,0.628343,Y,AY,275,360.522388,9.943284
1599,22423,3494,1.722880,0.749365,44534.26,12.781810,5,272,31,247.616769,...,11.379191,13,0.018419,A,0.434949,X,AX,231,268.769231,21.069231
3786,84879,26243,12.082413,6.159490,44302.67,1.688232,2,367,11,1323.300351,...,38.537701,38,0.023528,A,0.509790,Y,AY,304,690.605263,-82.281579
244,20725,19743,8.319848,5.311393,32585.55,1.657585,1,192,13,763.660819,...,17.083646,9,0.027286,A,0.638400,Y,AY,86,2193.666667,-619.800000

In [37]:
# =========================================================
# 🚨 Dead Stock Products
# =========================================================

dead_stock = inventory_df.sort_values(
    by="DeadStockScore",
    ascending=False
)

dead_stock.head(10)

,SKU,TotalDemand,AvgDemand,DemandStd,AnnualRevenue,AvgUnitPrice,LeadTime,OrderingCost,HoldingCost,EOQ,...,ReorderPoint,current_stock,CumulativeRevenue,ABC_Class,CV,XYZ_Class,ABC_XYZ,DaysSinceSale,TurnoverRatio,DeadStockScore
39,16044,48,48.000000,0.000000,20.16,0.420000,10,149,45,17.828816,...,480.000000,247,0.999729,C,0.000000,X,CX,359,0.194332,157.041700
352,20870,26,6.500000,8.020806,39.30,1.887500,11,420,49,21.111947,...,115.393308,93,0.999132,C,1.233970,Z,CZ,356,0.279570,157.016129
332,20847,47,2.611111,1.377931,176.25,3.750000,2,301,48,24.278763,...,8.437558,8,0.990318,C,0.527718,Y,CY,360,5.875000,156.637500
3537,84568,97,48.500000,67.175144,20.37,0.210000,13,488,40,48.649769,...,1030.135654,618,0.999715,C,1.385055,Z,CZ,361,0.156958,156.352913
3750,84847,83,2.371429,2.030441,306.45,3.727143,10,412,47,38.146414,...,34.308634,26,0.980021,C,0.856210,Y,CY,358,3.192308,156.342308
2634,23520,81,2.892857,2.298780,303.75,3.750000,14,59,45,14.573949,...,54.692061,29,0.980337,C,0.794640,Y,CY,359,2.793103,156.262069
342,20860,19,1.900000,1.370320,39.90,2.100000,3,138,48,10.452272,...,9.616216,10,0.999100,C,0.721221,Y,CY,356,1.900000,156.230000
4578,DOT,3,1.000000,0.000000,40.79,13.596667,7,148,44,4.492418,...,7.000000,4,0.999072,C,0.000000,X,CX,358,0.750000,156.175000
639,21268,359,8.975000,16.362069,159.18,0.546000,12,357,42,78.121700,...,201.221786,127,0.991627,C,1.823072,Z,CZ,361,2.826772,156.151969
2044,22891,398,2.707483,1.724961,1768.26,4.524830,11,389,46,82.045057,...,39.222045,47,0.810621,B,0.637109,Y,BY,362,8.468085,156.059574

In [38]:
# =========================================================
# 📊 ABC Distribution
# =========================================================

fig = px.histogram(

    inventory_df,
    x="ABC_Class",
    color="ABC_Class",
    title="ABC Inventory Classification"

)

fig.show()

In [39]:
# =========================================================
# 📊 XYZ Distribution
# =========================================================

fig = px.histogram(

    inventory_df,
    x="XYZ_Class",
    color="XYZ_Class",
    title="XYZ Demand Variability"

)

fig.show()

In [40]:
# =========================================================
# 📦 EOQ Distribution
# =========================================================

fig = px.box(

    inventory_df,
    y="EOQ",
    title="EOQ Distribution"

)

fig.show()

In [41]:
# =========================================================
# 💾 Export Inventory Intelligence Dataset
# =========================================================

inventory_df.to_csv(
    "../data/exports/inventory_intelligence.csv",
    index=False
)

print("✅ Inventory Intelligence Dataset Saved")

✅ Inventory Intelligence Dataset Saved

In [42]:
# =========================================================
# 📦 Inventory Feature Engineering
# =========================================================

# Create inventory-level aggregation

inventory_df = df.groupby(
    'stockcode'
).agg({

    'quantity': 'sum',

    'totalprice': 'sum',

    'invoiceno': 'count',

    'unitprice': 'mean'

}).reset_index()

inventory_df.columns = [

    'product',

    'annual_demand',

    'annual_revenue',

    'order_frequency',

    'unit_price'

]

inventory_df['daily_demand'] = (
    inventory_df['annual_demand'] / 365
)

# Simulated operational features

inventory_df['ordering_cost'] = 50

inventory_df['holding_cost'] = (
    inventory_df['unit_price'] * 0.15
)

inventory_df['lead_time_days'] = 7

inventory_df['current_stock'] = (
    inventory_df['annual_demand'] * 0.15
)

inventory_df['monthly_sales'] = (
    inventory_df['annual_demand'] / 12
)

inventory_df['demand_std'] = (
    inventory_df['daily_demand'] * 0.30
)

inventory_df.head()

,product,annual_demand,annual_revenue,order_frequency,unit_price,daily_demand,ordering_cost,holding_cost,lead_time_days,current_stock,monthly_sales,demand_std
0,10002,3225,2724.87,275,0.847636,8.835616,50,0.127145,7,483.75,268.750000,2.650685
1,10080,303,124.61,27,0.509259,0.830137,50,0.076389,7,45.45,25.250000,0.249041
2,10109,4,1.68,1,0.420000,0.010959,50,0.063000,7,0.60,0.333333,0.003288
3,10120,648,136.08,62,0.210000,1.775342,50,0.031500,7,97.20,54.000000,0.532603
4,10123C,532,175.88,45,0.623778,1.457534,50,0.093567,7,79.80,44.333333,0.437260

In [43]:
# =========================================================
# 📦 Economic Order Quantity (EOQ)
# =========================================================

import numpy as np

def calculate_eoq(
    demand,
    ordering_cost,
    holding_cost
):

    return np.sqrt(
        (2 * demand * ordering_cost)
        / holding_cost
    )

inventory_df['EOQ'] = inventory_df.apply(

    lambda row: calculate_eoq(

        row['annual_demand'],

        row['ordering_cost'],

        row['holding_cost']

    ),

    axis=1
)

inventory_df[
    ['product', 'EOQ']
].head()

  product          EOQ
0   10002  1592.628342
1   10080   629.805165
2   10109    79.681907
3   10120  1434.274331
4  10123C   754.041480

In [44]:
# =========================================================
# 🛡️ Safety Stock Calculation
# =========================================================

z_score = 1.65

inventory_df['Safety_Stock'] = (

    z_score *

    inventory_df['demand_std']

    *

    np.sqrt(
        inventory_df['lead_time_days']
    )

)

inventory_df[
    ['product', 'Safety_Stock']
].head()

  product  Safety_Stock
0   10002     11.571538
1   10080      1.087186
2   10109      0.014352
3   10120      2.325072
4  10123C      1.908855

In [45]:
# =========================================================
# 🔄 Reorder Point Calculation
# =========================================================

inventory_df['ReorderPoint'] = (

    inventory_df['daily_demand']

    *

    inventory_df['lead_time_days']

) + inventory_df['Safety_Stock']

inventory_df[
    ['product', 'ReorderPoint']
].head()

  product  ReorderPoint
0   10002     73.420853
1   10080      6.898145
2   10109      0.091065
3   10120     14.752469
4  10123C     12.111595

In [46]:
# =========================================================
# 🚨 Reorder Alert Engine
# =========================================================

inventory_df['Reorder_Alert'] = (

    inventory_df['current_stock']

    <

    inventory_df['ReorderPoint']
)

In [47]:
inventory_df[
    inventory_df['Reorder_Alert'] == True
].head()

Empty DataFrame
Columns: [product, annual_demand, annual_revenue, order_frequency, unit_price, daily_demand, ordering_cost, holding_cost, lead_time_days, current_stock, monthly_sales, demand_std, EOQ, Safety_Stock, ReorderPoint, Reorder_Alert]
Index: []

In [49]:
inventory_df[[
    'current_stock',
    'ReorderPoint'
]].describe()

       current_stock  ReorderPoint
count    4585.000000   4585.000000
mean      181.400513     27.531949
std       371.622699     56.402802
min         0.150000      0.022766
25%        10.650000      1.616397
50%        52.800000      8.013687
75%       187.500000     28.457695
max      6979.350000   1059.286467

In [50]:
# =========================================================
# 📊 ABC Inventory Classification
# =========================================================

revenue = inventory_df.groupby(
    'product'
)['annual_revenue'].sum()

sorted_revenue = revenue.sort_values(
    ascending=False
)

cumulative_percentage = (

    sorted_revenue.cumsum()

    /

    sorted_revenue.sum()

)

abc_class = []

for value in cumulative_percentage:

    if value <= 0.80:

        abc_class.append('A')

    elif value <= 0.95:

        abc_class.append('B')

    else:

        abc_class.append('C')

abc_inventory = pd.DataFrame({

    'Revenue': sorted_revenue,

    'ABC_Class': abc_class

})

abc_inventory.head()

          Revenue ABC_Class
product
85123A   66919.40         A
85099B   48247.80         A
22423    44534.26         A
84879    44302.67         A
20725    32585.55         A

In [51]:
# =========================================================
# 📈 XYZ Demand Variability Classification
# =========================================================

inventory_df['CV'] = (

    inventory_df['demand_std']

    /

    inventory_df['daily_demand']

)

def xyz_classification(cv):

    if cv <= 0.5:

        return 'X'

    elif cv <= 1.0:

        return 'Y'

    else:

        return 'Z'

inventory_df['XYZ_Class'] = (

    inventory_df['CV']

    .apply(xyz_classification)

)

inventory_df[
    ['product', 'XYZ_Class']
].head()

  product XYZ_Class
0   10002         X
1   10080         X
2   10109         X
3   10120         X
4  10123C         X

In [55]:
# =========================================================
# ⚠️ Inventory Risk Score
# =========================================================

inventory_df['Inventory_Risk_Score'] = (

    (
        inventory_df['ReorderPoint']

        -

        inventory_df['current_stock']
    )

    /

    inventory_df['ReorderPoint']

)

inventory_df[
    ['product', 'Inventory_Risk_Score']
].head()

  product  Inventory_Risk_Score
0   10002             -5.588728
1   10080             -5.588728
2   10109             -5.588728
3   10120             -5.588728
4  10123C             -5.588728

In [56]:
# =========================================================
# ☠️ Dead Stock Detection
# =========================================================

inventory_df['Dead_Stock'] = (

    inventory_df['monthly_sales']

    <= 1

)

dead_stock_items = inventory_df[
    inventory_df['Dead_Stock'] == True
]

dead_stock_items.head()

,product,annual_demand,annual_revenue,order_frequency,unit_price,daily_demand,ordering_cost,holding_cost,lead_time_days,current_stock,monthly_sales,demand_std,EOQ,Safety_Stock,ReorderPoint,Reorder_Alert,CV,XYZ_Class,Inventory_Risk_Score,Dead_Stock
2,10109,4,1.68,1,0.42,0.010959,50,0.0630,7,0.60,0.333333,0.003288,79.681907,0.014352,0.091065,False,0.3,X,-5.588728,True
51,16151A,9,18.75,4,2.50,0.024658,50,0.3750,7,1.35,0.750000,0.007397,48.989795,0.032293,0.204895,False,0.3,X,-5.588728,True
85,16215,8,5.20,3,0.65,0.021918,50,0.0975,7,1.20,0.666667,0.006575,90.582163,0.028705,0.182129,False,0.3,X,-5.588728,True
95,16244A,7,29.75,4,4.25,0.019178,50,0.6375,7,1.05,0.583333,0.005753,33.136675,0.025117,0.159363,False,0.3,X,-5.588728,True
97,16245A,11,13.75,7,1.25,0.030137,50,0.1875,7,1.65,0.916667,0.009041,76.594169,0.039469,0.250428,False,0.3,X,-5.588728,True

In [57]:
# =========================================================
# 📊 Inventory Intelligence Summary
# =========================================================

total_products = len(inventory_df)

reorder_products = np.sum(
    inventory_df['Reorder_Alert']
    
)

dead_stock_count = np.sum(
    inventory_df['Dead_Stock']
)

high_risk_inventory = np.sum(
    inventory_df['Inventory_Risk_Score'] > 0.30
)

print(
    f"Total Products: {total_products}"
)

print(
    f"Reorder Alerts: {reorder_products}"
)

print(
    f"Dead Stock Products: {dead_stock_count}"
)

print(
    f"High Risk Inventory: "
    f"{high_risk_inventory}"
)

Total Products: 4585
Reorder Alerts: 0
Dead Stock Products: 398
High Risk Inventory: 0

In [58]:
# =========================================================
# ⚠️ Stable Inventory Risk Score
# =========================================================

inventory_df['Inventory_Risk_Score'] = np.where(

    inventory_df['ReorderPoint'] > 0,

    (
        inventory_df['ReorderPoint']
        -
        inventory_df['current_stock']
    )

    /

    inventory_df['ReorderPoint'],

    0
)

inventory_df[
    'Inventory_Risk_Score'
] = inventory_df[
    'Inventory_Risk_Score'
].clip(0, 1)

inventory_df[
    ['product', 'Inventory_Risk_Score']
].head()

  product  Inventory_Risk_Score
0   10002                   0.0
1   10080                   0.0
2   10109                   0.0
3   10120                   0.0
4  10123C                   0.0

In [73]:
# =========================================================
# STOCK COVERAGE RISK
# =========================================================

inventory_df['Stock_Coverage_Days'] = (

    inventory_df['current_stock']

    /

    (inventory_df['daily_demand'] + 1)
)

# Risk logic
inventory_df['Inventory_Risk_Score'] = np.where(

    inventory_df['Stock_Coverage_Days'] < 7,

    90,

    np.where(

        inventory_df['Stock_Coverage_Days'] < 15,

        70,

        np.where(

            inventory_df['Stock_Coverage_Days'] < 30,

            40,

            10
        )
    )
)

In [74]:
inventory_df['Inventory_Risk_Score'].value_counts()

Inventory_Risk_Score
10    2087
90     997
40     924
70     577
Name: count, dtype: int64

In [75]:
# =========================================================
# 💾 Export Inventory Intelligence
# =========================================================

inventory_df.to_csv(

    '../data/exports/inventory_intelligence_report.csv',

    index=False

)

print(
    "Inventory Intelligence Report Saved"
)

Inventory Intelligence Report Saved

In [77]:
# =========================================================
# Export Inventory Intelligence
# =========================================================

inventory_export = inventory_df[[

    'product',

    'current_stock',

    'ReorderPoint',

    'EOQ',

    'Inventory_Risk_Score'
]]

inventory_export.to_csv(

   r"D:\NuralRetail\app\dashboard\data\inventory_risk.csv",

    index=False
)

print("✅ inventory_risk.csv exported successfully")

✅ inventory_risk.csv exported successfully

In [78]:
inventory_df['Inventory_Risk_Score'].value_counts()

Inventory_Risk_Score
10    2087
90     997
40     924
70     577
Name: count, dtype: int64